version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: shimahome_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-shimahome}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-shimahome}
      POSTGRES_DB: ${POSTGRES_DB:-shimahome}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-shimahome}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: shimahome_redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
